apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shopnow-database-services
  namespace: argocd
  labels:
    app.kubernetes.io/name: shopnow-database-services
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: shopnow
  source:
    repoURL: https://github.com/tranvix0910/shopnow-manifest.git
    targetRevision: HEAD
    path: kustomize
  destination:
    server: https://kubernetes.default.svc
    namespace: shopnow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10 