apiVersion: v1
kind: Namespace
metadata:
  name: shopnow
  labels:
    name: shopnow
    app.kubernetes.io/name: shopnow
    app.kubernetes.io/component: namespace
  annotations:
    description: "ShopNow application namespace for database services" 