apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopnow-keycloak-realms-deployment
  namespace: shopnow
  labels:
    app: shopnow-keycloak-realms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopnow-keycloak-realms
  template:
    metadata:
      labels:
        app: shopnow-keycloak-realms
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:23.0.3
          command:
            - "/opt/keycloak/bin/kc.sh"
            - "start-dev"
            - "--import-realm"
          env:
            - name: DB_VENDOR
              value: MYSQL
            - name: DB_ADDR
              value: shopnow-keycloak-mysql-service
            - name: DB_DATABASE
              value: keycloak
            - name: DB_USER
              value: keycloak
            - name: DB_PASSWORD
              value: password
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: admin
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - mountPath: /opt/keycloak/data/import
              name: keycloak-realms
              subPath: keycloak-realms
            - mountPath: /opt/keycloak/data/import/realm-export.json
              name: realm-config
              subPath: realm-export.json
              readOnly: true
      volumes:
        - name: keycloak-realms
          persistentVolumeClaim:
            claimName: keycloak-realms-pvc
        - name: realm-config
          configMap:
            name: keycloak-realm-config
            optional: true
            
---

apiVersion: v1
kind: Service
metadata:
  name: shopnow-keycloak-realms-service
  namespace: shopnow
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: shopnow-keycloak-realms
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shopnow-keycloak-realms-ingress
  namespace: shopnow
  annotations:
    # SSL Redirect Configuration
    alb.ingress.kubernetes.io/actions.ssl-redirect: |
      {
        "Type": "redirect",
        "RedirectConfig": {
          "Protocol": "HTTPS",
          "Port": "443",
          "Host": "#{host}",
          "Path": "/#{path}",
          "Query": "#{query}",
          "StatusCode": "HTTP_301"
        }
      }
    
    # SSL Certificate
    alb.ingress.kubernetes.io/certificate-arn: |
      arn:aws:acm:ap-southeast-1:022499043310:certificate/647360bb-b2ea-4ec5-9551-2da20236dd16
    
    # ALB Configuration
    alb.ingress.kubernetes.io/group.name: shopnow-keycloak-realms
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    
    # Subnet Configuration
    alb.ingress.kubernetes.io/subnets: |
      subnet-00502d28cf8623a99,
      subnet-00f29dc65958e83c4,
      subnet-0b4dd832c80661a42
spec:
  ingressClassName: alb
  rules:
    - host: keycloak-shopnow.tranvix.click
      http:
        paths:
          - backend:
              service:
                name: shopnow-keycloak-realms-service
                port:
                  number: 8080
            path: /
            pathType: Prefix