apiVersion: v1
kind: ConfigMap
metadata:
  name: shopnow-user-service-application-properties-configmap
  namespace: shopnow
data:
  application.properties: |
    # Application configuration
    spring.application.name=user-service
    server.port=5865

    eureka.instance.hostname=user-service
    eureka.instance.instance-id=${spring.application.name}
    eureka.client.service-url.defaultZone=http://shopnow-discovery-server-service:8761/eureka/

    # Datasource configuration
    spring.datasource.url=jdbc:postgresql://postgres:5432/postgres?useSSL=false
    spring.datasource.username=postgres
    spring.datasource.password=admin
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=true
    spring.jpa.properties.hibernate.format-sql=true

    # JWT configuration
    jwt.issuer_uri=http://shopnow-keycloak-realms-service:8080/realms/java-microservice-realm/protocol/openid-connect/token
    jwt.client_id=spring-cloud-client
    jwt.client_secret=AJufwN1eof8P5Gga5Y9atCFqdMuZEuKd
    jwt.grant_type=client_credentials
    jwt.scope=openid offline_access
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: shopnow-user-service
  name: shopnow-user-service-deployment
  namespace: shopnow
spec:
  replicas: 1
  revisionHistoryLimit: 11
  selector:
    matchLabels:
      app: shopnow-user-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: shopnow-user-service
      namespace: shopnow
    spec:
      containers:
        - image: harbor.tranvix.click/shopnow/service-user:v1
          imagePullPolicy: Always
          name: shopnow-user-service
          ports:
            - containerPort: 5865
              name: tcp
              protocol: TCP
          volumeMounts:
            - mountPath: /app/src/main/resources/application.properties
              name: shopnow-user-service-application-properties-config-volume
              subPath: application.properties
      imagePullSecrets:
      - name: shopnow-registry-secret
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - configMap:
            defaultMode: 420
            name: shopnow-user-service-application-properties-configmap
          name: shopnow-user-service-application-properties-config-volume
---
apiVersion: v1
kind: Service
metadata:
  name: shopnow-user-service-service
  namespace: shopnow
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: tcp
      port: 5865
      protocol: TCP
      targetPort: 5865
  selector:
    app: shopnow-user-service
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shopnow-user-service-ingress
  namespace: shopnow
spec:
  ingressClassName: nginx
  rules:
    - host: user-service-shopnow.tranvix.click
      http:
        paths:
          - backend:
              service:
                name: shopnow-user-service-service
                port:
                  number: 5865
            path: /
            pathType: Prefix
